---
- name: Generating random password
  set_fact:
    password: "{{ lookup('password', '../lastpass.txt') }}"

- local_action: shell rm lastpass.txt

- name: Setting password
  shell: (echo '{{ password }}'; sleep 1; echo '{{ password }}') | passwd root
